### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Quimoniz** [EEESlab/examon#1]
I followed the instructions provided in the README on Installation/Building.

However this error appears:
```
make[2]: Entering directory '/home/jitschin/git/examon/lib/mosquitto-1.3.5/client'
cc pub_client.o -o mosquitto_pub  -L../lib ../lib/libmosquitto.so.1
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_num'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_ssl'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_value'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_crypto'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
Makefile:8: recipe for target 'mosquitto_pub' failed
make[2]: *** [mosquitto_pub] Error 1
make[2]: Leaving directory '/home/jitschin/git/examon/lib/mosquitto-1.3.5/client'
Makefile:17: recipe for target 'mosquitto' failed

```

It sounded to me like there could be some issue with OpenSSL. So I reinstalled openssl `sudo apt-get install --reinstall libssl-dev`. Nothing changed. So I figured I could fetch a more recent OpenSSL, like version 1.1.1. I built it and installed it. However building examon still failed **with the same error**.

I am running Ubuntu 16.04.4 LTS. `uname -a` gives me the following:
`4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Here is a full listing of what make told me upon invocation: https://pastebin.com/HZxKRdn2

I would be happy for a response within the next days.  Even a mere hint to a solution would be appreciated.

**Comment by fbeneventi** [comment]
Hi, 
this issue is discussed here:
https://github.com/eclipse/mosquitto/issues/570

This comment looks like a solution
https://github.com/eclipse/mosquitto/issues/570#issuecomment-351249437

Please check and let me know if it solves also for you

**Comment by Quimoniz** [comment]
Thank you for the quick response.

It worked. Thanks! :)
