### ISSUE TITLE
Difficulties (segmentation fault)

### ISSUE THREAD

**Issue by Quimoniz** [EEESlab/examon#2]
Thanks again for your quick mail-response. Sorry it took me a bit to compile this issue, I had to make sure the error wasn't due to some strange configuration on the test system.

I ran EXAMON on a test system, a [HASWELL](https://ark.intel.com/products/75122/Intel-Core-i7-4770-Processor-8M-Cache-up-to-3_90-GHz), using mod msr and mosquitto, both with and without kpti patch (i.e. tried it with kernel option `nopti`). Each time it segfaulted in the same function: [rdpmc ()](https://github.com/EEESlab/examon/blob/master/publishers/pmu_pub/sensor_read_lib.c#L89)

I compiled EXAMON with options `-DDEBUG=True` and `-g` and ran it through gdb. It told me a few more details about the segfault, here's what I got: https://pastebin.com/qzwmaLmv

The Linux version I am running according to uname -a is `Linux mabus 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Could it be that the CPU (with family 6, model 60) is not supported?

Which steps could I take to get EXAMON running on said CPU?

Should I test EXAMON on a different CPU e.g. one of Ivy Bridge, Westmere EP, Skylake, Sandy Bridge, Sandy Bridge EP or another Haswell?

**Comment by fbeneventi** [comment]
The pmu_pub plugin is designed to work in dual socket systems and Xeon class processors.
However it could work also on a notebook but this was not fully tested.

Anyway, the problem of the rdpmc instruction and 4.x kernels could be strictly related to [this ](https://github.com/EEESlab/countdown#enable-rdpmc---required-only-for-systems-with-kernel-4x).

**Comment by Quimoniz** [comment]
I tested it on [another Haswell](https://ark.intel.com/products/81908/Intel-Xeon-Processor-E5-2680-v3-30M-Cache-2_50-GHz), it has 2 sockets and is a XEON processor. I used Linux kernel 4.13.0-16.

I had to activate rdpmc on it manually, too. Besides that it works just fine.

I am really happy about seeing information flowing over MQTT.

Thanks for the help :)
